use crate::domain::entities::{
    FingerprintDefinition, FingerprintRule, FingerprintTier, RuleCategory, RuleWeight,
};

/// Returns the full catalog of known service fingerprints with
/// reliability tiers, rule weights, and contextual dependencies.
pub fn load_registry() -> Vec<FingerprintDefinition> {
    vec![
        // ═══════════════ SPECIFIC TIER ═══════════════

        // ── SSH ──
        FingerprintDefinition {
            id: "ssh-generic".into(),
            service_name: "SSH".into(),
            description: "OpenSSH or compatible SSH server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.25,
            rules: vec![
                rule(
                    RuleCategory::BannerStartsWith,
                    "SSH-",
                    0.45,
                    RuleWeight::Critical,
                    true,
                    "SSH protocol greeting",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "22",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard SSH port",
                    None,
                ),
                rule(
                    RuleCategory::BannerContains,
                    "OpenSSH",
                    0.15,
                    RuleWeight::Strong,
                    false,
                    "OpenSSH vendor signature",
                    Some(RuleCategory::BannerStartsWith),
                ),
            ],
        },
        // ── FTP ──
        FingerprintDefinition {
            id: "ftp-generic".into(),
            service_name: "FTP".into(),
            description: "FTP server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.25,
            rules: vec![
                rule(
                    RuleCategory::BannerStartsWith,
                    "220",
                    0.20,
                    RuleWeight::Medium,
                    true,
                    "FTP 220 ready greeting",
                    None,
                ),
                rule(
                    RuleCategory::BannerContains,
                    "FTP",
                    0.30,
                    RuleWeight::Strong,
                    false,
                    "FTP keyword in banner",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "21",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard FTP port",
                    None,
                ),
            ],
        },
        // ── SMTP ──
        FingerprintDefinition {
            id: "smtp-generic".into(),
            service_name: "SMTP".into(),
            description: "SMTP mail server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.25,
            rules: vec![
                rule(
                    RuleCategory::BannerContains,
                    "SMTP",
                    0.35,
                    RuleWeight::Critical,
                    true,
                    "SMTP keyword in banner",
                    None,
                ),
                rule(
                    RuleCategory::BannerStartsWith,
                    "220",
                    0.15,
                    RuleWeight::Medium,
                    false,
                    "SMTP 220 greeting",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "25",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard SMTP port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "465",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "SMTPS port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "587",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "Submission port",
                    None,
                ),
            ],
        },
        // ── IMAP ──
        FingerprintDefinition {
            id: "imap-generic".into(),
            service_name: "IMAP".into(),
            description: "IMAP mail server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.25,
            rules: vec![
                rule(
                    RuleCategory::BannerStartsWith,
                    "* OK",
                    0.35,
                    RuleWeight::Critical,
                    true,
                    "IMAP OK greeting",
                    None,
                ),
                rule(
                    RuleCategory::BannerContains,
                    "IMAP",
                    0.20,
                    RuleWeight::Strong,
                    false,
                    "IMAP keyword",
                    Some(RuleCategory::BannerStartsWith),
                ),
                rule(
                    RuleCategory::PortBinding,
                    "143",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard IMAP port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "993",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "IMAPS port",
                    None,
                ),
            ],
        },
        // ── POP3 ──
        FingerprintDefinition {
            id: "pop3-generic".into(),
            service_name: "POP3".into(),
            description: "POP3 mail server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.25,
            rules: vec![
                rule(
                    RuleCategory::BannerStartsWith,
                    "+OK",
                    0.35,
                    RuleWeight::Critical,
                    true,
                    "POP3 +OK greeting",
                    None,
                ),
                rule(
                    RuleCategory::BannerContains,
                    "POP3",
                    0.15,
                    RuleWeight::Strong,
                    false,
                    "POP3 keyword",
                    Some(RuleCategory::BannerStartsWith),
                ),
                rule(
                    RuleCategory::PortBinding,
                    "110",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard POP3 port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "995",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "POP3S port",
                    None,
                ),
            ],
        },
        // ── HTTPS ──
        FingerprintDefinition {
            id: "https-web".into(),
            service_name: "HTTPS".into(),
            description: "TLS-secured HTTP web server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.30,
            rules: vec![
                rule(
                    RuleCategory::TlsPresent,
                    "true",
                    0.30,
                    RuleWeight::Critical,
                    true,
                    "TLS handshake succeeded",
                    None,
                ),
                rule(
                    RuleCategory::HttpStatusRange,
                    "100-599",
                    0.25,
                    RuleWeight::Strong,
                    false,
                    "Valid HTTP response over TLS",
                    Some(RuleCategory::TlsPresent),
                ),
                rule(
                    RuleCategory::TlsAlpnContains,
                    "h2",
                    0.10,
                    RuleWeight::Strong,
                    false,
                    "HTTP/2 ALPN negotiated",
                    Some(RuleCategory::TlsPresent),
                ),
                rule(
                    RuleCategory::TlsAlpnContains,
                    "http/1.1",
                    0.08,
                    RuleWeight::Medium,
                    false,
                    "HTTP/1.1 ALPN",
                    Some(RuleCategory::TlsPresent),
                ),
                rule(
                    RuleCategory::PortBinding,
                    "443",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "Standard HTTPS port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "8443",
                    0.06,
                    RuleWeight::Weak,
                    false,
                    "Alt HTTPS port",
                    None,
                ),
                rule(
                    RuleCategory::HttpServerContains,
                    "",
                    0.05,
                    RuleWeight::Contextual,
                    false,
                    "Server header present",
                    Some(RuleCategory::HttpStatusRange),
                ),
            ],
        },
        // ── HTTP (plain) ──
        FingerprintDefinition {
            id: "http-plain".into(),
            service_name: "HTTP".into(),
            description: "Plain HTTP web server (no TLS)".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.25,
            rules: vec![
                rule(
                    RuleCategory::HttpStatusRange,
                    "100-599",
                    0.35,
                    RuleWeight::Critical,
                    true,
                    "Valid HTTP response",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "80",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard HTTP port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "8080",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "Alt HTTP port",
                    None,
                ),
                rule(
                    RuleCategory::HttpServerContains,
                    "",
                    0.05,
                    RuleWeight::Contextual,
                    false,
                    "Server header present",
                    Some(RuleCategory::HttpStatusRange),
                ),
                rule(
                    RuleCategory::HttpContentTypeContains,
                    "text/html",
                    0.10,
                    RuleWeight::Medium,
                    false,
                    "HTML content served",
                    Some(RuleCategory::HttpStatusRange),
                ),
            ],
        },
        // ── MySQL ──
        FingerprintDefinition {
            id: "mysql-generic".into(),
            service_name: "MySQL".into(),
            description: "MySQL or MariaDB database server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.30,
            rules: vec![
                rule(
                    RuleCategory::GreetingSignature,
                    "mysql",
                    0.50,
                    RuleWeight::Critical,
                    true,
                    "MySQL handshake v10 greeting",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "3306",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard MySQL port",
                    None,
                ),
                rule(
                    RuleCategory::BannerContains,
                    "MariaDB",
                    0.10,
                    RuleWeight::Strong,
                    false,
                    "MariaDB variant",
                    Some(RuleCategory::GreetingSignature),
                ),
            ],
        },
        // ── PostgreSQL ──
        FingerprintDefinition {
            id: "postgresql-generic".into(),
            service_name: "PostgreSQL".into(),
            description: "PostgreSQL database server".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.30,
            rules: vec![
                rule(
                    RuleCategory::GreetingSignature,
                    "postgresql",
                    0.50,
                    RuleWeight::Critical,
                    true,
                    "PostgreSQL auth packet",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "5432",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard PostgreSQL port",
                    None,
                ),
            ],
        },
        // ── Redis ──
        FingerprintDefinition {
            id: "redis-generic".into(),
            service_name: "Redis".into(),
            description: "Redis in-memory data store".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.30,
            rules: vec![
                rule(
                    RuleCategory::GreetingSignature,
                    "redis",
                    0.45,
                    RuleWeight::Critical,
                    true,
                    "Redis RESP signature",
                    None,
                ),
                rule(
                    RuleCategory::BannerContains,
                    "REDIS",
                    0.15,
                    RuleWeight::Strong,
                    false,
                    "Redis keyword in banner",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "6379",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Standard Redis port",
                    None,
                ),
            ],
        },
        // ── RDP ──
        FingerprintDefinition {
            id: "rdp-generic".into(),
            service_name: "RDP".into(),
            description: "Microsoft Remote Desktop Protocol".into(),
            tier: FingerprintTier::Specific,
            min_confidence: 0.20,
            rules: vec![
                rule(
                    RuleCategory::PortBinding,
                    "3389",
                    0.15,
                    RuleWeight::Medium,
                    true,
                    "Standard RDP port",
                    None,
                ),
                rule(
                    RuleCategory::TlsPresent,
                    "true",
                    0.15,
                    RuleWeight::Medium,
                    false,
                    "RDP often uses TLS",
                    None,
                ),
            ],
        },
        // ═══════════════ GENERIC TIER ═══════════════

        // ── Generic Web Server ──
        FingerprintDefinition {
            id: "generic-web".into(),
            service_name: "Web Server".into(),
            description: "HTTP-responding service, type unknown".into(),
            tier: FingerprintTier::Generic,
            min_confidence: 0.15,
            rules: vec![
                rule(
                    RuleCategory::HttpStatusRange,
                    "100-599",
                    0.30,
                    RuleWeight::Medium,
                    true,
                    "Any HTTP response received",
                    None,
                ),
                rule(
                    RuleCategory::HttpServerContains,
                    "",
                    0.10,
                    RuleWeight::Weak,
                    false,
                    "Server header present",
                    Some(RuleCategory::HttpStatusRange),
                ),
            ],
        },
        // ── Generic Database ──
        FingerprintDefinition {
            id: "generic-database".into(),
            service_name: "Database".into(),
            description: "Database-like greeting detected".into(),
            tier: FingerprintTier::Generic,
            min_confidence: 0.15,
            rules: vec![
                rule(
                    RuleCategory::GreetingSignature,
                    "",
                    0.25,
                    RuleWeight::Medium,
                    true,
                    "Any database greeting pattern",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "3306",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "MySQL port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "5432",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "PostgreSQL port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "6379",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "Redis port",
                    None,
                ),
            ],
        },
        // ── Generic Mail ──
        FingerprintDefinition {
            id: "generic-mail".into(),
            service_name: "Mail Server".into(),
            description: "Mail-related service detected".into(),
            tier: FingerprintTier::Generic,
            min_confidence: 0.15,
            rules: vec![
                rule(
                    RuleCategory::BannerStartsWith,
                    "220",
                    0.20,
                    RuleWeight::Medium,
                    true,
                    "220 greeting (SMTP/FTP)",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "25",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "Mail port",
                    None,
                ),
                rule(
                    RuleCategory::PortBinding,
                    "587",
                    0.08,
                    RuleWeight::Weak,
                    false,
                    "Submission port",
                    None,
                ),
            ],
        },
        // ═══════════════ FALLBACK TIER ═══════════════

        // ── Unknown TLS ──
        FingerprintDefinition {
            id: "tls-unknown".into(),
            service_name: "Unknown TLS".into(),
            description: "TLS-secured service, protocol unknown".into(),
            tier: FingerprintTier::Fallback,
            min_confidence: 0.10,
            rules: vec![rule(
                RuleCategory::TlsPresent,
                "true",
                0.25,
                RuleWeight::Medium,
                true,
                "TLS handshake succeeded",
                None,
            )],
        },
        // ── DNS ──
        FingerprintDefinition {
            id: "dns-generic".into(),
            service_name: "DNS".into(),
            description: "DNS server".into(),
            tier: FingerprintTier::Fallback,
            min_confidence: 0.10,
            rules: vec![rule(
                RuleCategory::PortBinding,
                "53",
                0.20,
                RuleWeight::Weak,
                true,
                "Standard DNS port",
                None,
            )],
        },
        // ── MSSQL ──
        FingerprintDefinition {
            id: "mssql-generic".into(),
            service_name: "MSSQL".into(),
            description: "Microsoft SQL Server".into(),
            tier: FingerprintTier::Fallback,
            min_confidence: 0.10,
            rules: vec![rule(
                RuleCategory::PortBinding,
                "1433",
                0.20,
                RuleWeight::Weak,
                true,
                "Standard MSSQL port",
                None,
            )],
        },
        // ── Oracle ──
        FingerprintDefinition {
            id: "oracle-generic".into(),
            service_name: "Oracle".into(),
            description: "Oracle Database listener".into(),
            tier: FingerprintTier::Fallback,
            min_confidence: 0.10,
            rules: vec![rule(
                RuleCategory::PortBinding,
                "1521",
                0.20,
                RuleWeight::Weak,
                true,
                "Standard Oracle port",
                None,
            )],
        },
        // ── NFS ──
        FingerprintDefinition {
            id: "nfs-generic".into(),
            service_name: "NFS".into(),
            description: "Network File System".into(),
            tier: FingerprintTier::Fallback,
            min_confidence: 0.10,
            rules: vec![rule(
                RuleCategory::PortBinding,
                "2049",
                0.20,
                RuleWeight::Weak,
                true,
                "Standard NFS port",
                None,
            )],
        },
    ]
}

fn rule(
    category: RuleCategory,
    value: &str,
    weight: f32,
    rule_weight: RuleWeight,
    required: bool,
    desc: &str,
    contextual_requires: Option<RuleCategory>,
) -> FingerprintRule {
    FingerprintRule {
        category,
        expected_value: value.to_string(),
        weight,
        rule_weight,
        required,
        description: desc.to_string(),
        contextual_requires,
    }
}
